/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectotrivia;

import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.*;
import javax.swing.JOptionPane;
/**
 *
 * @author JERO
 */
public class menuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(menuPrincipal.class.getName());

    /**
     * Creates new form menuPrincipal
     */
    public menuPrincipal() {
        
        initComponents();
        
        getContentPane().setBackground(new java.awt.Color(30, 58, 95));
         
        ImageIcon icon = new ImageIcon(
         getClass().getResource("/proyectotrivia/messi celebrando.png")
        );

        Image img = icon.getImage();
        Image imgEscalada = img.getScaledInstance(900, 500, Image.SCALE_SMOOTH);

        lblImagen.setIcon(new ImageIcon(imgEscalada));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnModo1 = new RoundedButton();
        btnModoDuelo = new RoundedButton();
        lblImagen = new javax.swing.JLabel();
        btnRegistro = new RoundedButton();
        btnInfo = new RoundedButton();
        btnHistorial = new RoundedButton();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setLocation(new java.awt.Point(0, 0));

        btnModo1.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        btnModo1.setText("MODO SOLITARIO");
        btnModo1.addActionListener(this::btnModo1ActionPerformed);

        btnModoDuelo.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        btnModoDuelo.setText("MODO DUELO");
        btnModoDuelo.addActionListener(this::btnModoDueloActionPerformed);

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectotrivia/messi celebrando.png"))); // NOI18N

        btnRegistro.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        btnRegistro.setText("REGISTRAR USUARIO");
        btnRegistro.addActionListener(this::btnRegistroActionPerformed);

        btnInfo.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        btnInfo.setText("INFORMACION");
        btnInfo.addActionListener(this::btnInfoActionPerformed);

        btnHistorial.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        btnHistorial.setText("HISTORIAL PARTIDAS");
        btnHistorial.addActionListener(this::btnHistorialActionPerformed);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        lblTitulo.setBackground(new java.awt.Color(51, 204, 255));
        lblTitulo.setFont(new java.awt.Font("Showcard Gothic", 0, 60)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("TRIVIA UAA GAME");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(560, 560, 560)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInfo)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModo1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnHistorial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                        .addComponent(btnRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModoDuelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(160, 160, 160)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnModo1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(btnModoDuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModo1ActionPerformed
        
        menuInicioSolitario m = new menuInicioSolitario();
        m.setLocationRelativeTo(null);
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnModo1ActionPerformed

    private void btnModoDueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModoDueloActionPerformed
        
         menuInicioDuelo m = new menuInicioDuelo();
         m.setLocationRelativeTo(null);
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnModoDueloActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        
        menuCargaUsuarios m = new menuCargaUsuarios();
         m.setLocationRelativeTo(null);
        m.setVisible(true);
        dispose();
        
        
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
         menuHistorialPartidas m = new menuHistorialPartidas();
         m.setLocationRelativeTo(null);
            m.setVisible(true);
            dispose();
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
        String mensaje = "¡Bienvenido a nuestro Juego de Trivia!\n\n"
                + "Cómo Jugar:\n\n"
                + "1. Modo Solitario: En este modo, jugarás contra tu propia habilidad. Responde las 5 preguntas como puedas y trata de conseguir la máxima puntuación.\n\n"
                + "2. Modo Duelo: En este modo, te enfrentarás a otro jugador en una competencia uno a uno. Cada respuesta correcta suma 100 puntos, y el que llegue más lejos será el ganador.\n\n"
                + "¡Demuestra tu conocimiento y diviértete con nosotros!"
                + "\n\n\nDesarrollada por Ezequiel Larrea y Jerónimo Perín, alumnos de la Universidad Atlantida Argentina.";
        
        JOptionPane.showMessageDialog(null, mensaje, "Información del Juego", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new menuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnModo1;
    private javax.swing.JButton btnModoDuelo;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
